[env:waveshare-esp32-s3-lcd-147]
board = esp32s3-16mb-psram
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/waveshare-esp32-s3-lcd-147>
build_src_flags =
	-DDISABLE_OTA
	-DWAVESHARE_ESP32_S3_LCD_147=1
	-DPART_16MB=1
	-DROTATION=1

	-DHAS_BTN=1
	-DSEL_BTN=0
	-DUP_BTN=-1
	-DDW_BTN=-1
	-DBTN_ACT=LOW

	-DBTN_ALIAS='"OK"'

	-DMINBRIGHT=1
	-DBACKLIGHT=48
	-DLED=38
	-DLED_ON=HIGH

	-DFP=1
	-DFM=2
	-DFG=3

	-DST7789_DRIVER=1
	-DUSER_SETUP_LOADED
	-DTFT_RGB_ORDER=TFT_BGR
	-DINIT_SEQUENCE_3
	-DCGRAM_OFFSET
	-DTFT_WIDTH=172
	-DTFT_HEIGHT=320
	-DTFT_MISO=-1
	-DTFT_MOSI=45
	-DTFT_SCLK=40
	-DTFT_CS=42
	-DTFT_DC=41
	-DTFT_RST=39
	-DTFT_BL=48
	-DTFT_BACKLIGHT_ON=HIGH
	-DGFX_BL=48
	-DTFT_IPS=1
	-DTFT_COL_OFS1=34
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=34
	-DTFT_ROW_OFS2=0
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	-DUSE_HSPI_PORT=1
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-DLOAD_FONT6=1
	-DLOAD_FONT7=1

	-DSDM=SD_MMC
	-DPIN_SD_CLK=14
	-DPIN_SD_CMD=15
	-DPIN_SD_D0=16

	-D SDCARD_CS=-1
	-D SDCARD_SCK=PIN_SD_CLK
	-D SDCARD_MISO=PIN_SD_D0
	-D SDCARD_MOSI=PIN_SD_CMD


