; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

##################################### NM-CYD-C5 (ESP32-C5) ####################################################
[env:NM-CYD-C5]
board = esp32c5-16mb-psram
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/NM-CYD-C5>
build_src_flags =
	-DDEVICE_NAME='"NM-CYD-C5"'
	-DOTA_TAG='"NM-CYD-C5"'
	-DHAS_TOUCH=1
	-DPART_16MB=1
	-DNM_CYD_C5
	-DDONT_USE_INPUT_TASK=1
	-DDIMMER_SETUP=60
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DROTATION=3
		; text sizes
	-DFP=1
	-DFM=2
	-DFG=3
	-DST7789_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_BL=25
	-DTFT_RST=-1
	-DTFT_DC=24
	-DTFT_MISO=2
	-DTFT_MOSI=7
	-DTFT_SCLK=6
	-DTFT_CS=23
	-DTOUCH_CS=1
	-DTFT_IPS=0
	-DTFT_COL_OFS1=0
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=0
	-DTFT_ROW_OFS2=0
	-D HAS_RESISTIVE_TOUCH=1
	-DCYD28_TouchR_CAL_XMIN=185
	-DCYD28_TouchR_CAL_XMAX=3700
	-DCYD28_TouchR_CAL_YMIN=250
	-DCYD28_TouchR_CAL_YMAX=3800
	-DCYD28_DISPLAY_HOR_RES_MAX=320
	-DCYD28_DISPLAY_VER_RES_MAX=240
	-DTOUCH_XPT2046_SPI=1
	-DCYD28_TouchR_IRQ=-1
	-DCYD28_TouchR_MISO=TFT_MISO
	-DCYD28_TouchR_MOSI=TFT_MOSI
	-DCYD28_TouchR_CLK=TFT_SCLK
	-DCYD28_TouchR_CS=1
	-DBOARD_HAS_TF=1
	-DSDCARD_CS=10
	-DSDCARD_SCK=TFT_SCLK
	-DSDCARD_MISO=TFT_MISO
	-DSDCARD_MOSI=TFT_MOSI

lib_ignore =
	SensorLib
	XPowersLib
