; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-dongle-s3-tft]
board = esp32s3-16mb-psram
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-dongle-s3-tft>
build_src_flags =
	-DDISABLE_OTA

	;-DPART_04MB =0
	;-DPART_08MB =0
	-DPART_16MB=1
    -DROTATION=1
    -DHAS_BTN=1
    -DSEL_BTN=0
	-DUP_BTN=-1
	-DDW_BTN=14
	-DBTN_ACT=HIGH
	-DBTN_ALIAS='"Sel"'
	-DMINBRIGHT=190
	-DBACKLIGHT=38
	-DLED=1
	-DLED_ON=HIGH

	-DFP=1
	-DFM=1
	-DFG=2

	-D  ST7735_DRIVER
	-D	ST7735_GREENTAB160x80=1
	-D  TFT_WIDTH=80
	-D  TFT_HEIGHT=160
	-D  TFT_MOSI=3
	-D  TFT_SCLK=5
	-D  TFT_CS=4
	-D  TFT_DC=2
	-D  TFT_RST=1


	-D GFX_BL=38
	-D TFT_IPS=1
	-D TFT_COL_OFS1=26
	-D TFT_ROW_OFS1=1
	-D TFT_COL_OFS2=26
	-D TFT_ROW_OFS2=1

	-DPIN_SD_CMD=16
	-DPIN_SD_CLK=12
	-DPIN_SD_D0=14
	-DPIN_SD_D1=17 # Not used, disabled in software
	-DPIN_SD_D2=21 # Not used, disabled in software
	-DPIN_SD_D3=18

	-DSDCARD_CS=PIN_SD_D3
	-DSDCARD_SCK=PIN_SD_CLK
	-DSDCARD_MISO=PIN_SD_D0
	-DSDCARD_MOSI=PIN_SD_CMD

	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=10000

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button

lib_ignore =
	SensorLib
	XPowersLib
