; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[elecrow]
board = esp32-4mb
board_build.partitions = support_files/custom_4Mb_noOta.csv
build_src_filter =${env.build_src_filter} +<../boards/elecrow>
build_src_flags =
	-DPART_04MB=1
	-DELECROW
	# Definições gerais
	-DOTA_TAG='"elecrow"'
	-DDISABLE_OTA

	# Configurações de hardware
	-DROTATION=1
	-DHAS_BTN=0
	-DSEL_BTN=-1
	-DUP_BTN=-1
	-DDW_BTN=-1
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"Sel"'
	-DMINBRIGHT=190
	-DBACKLIGHT=27
	-DLED=-1
	-DLED_ON=LOW
	-DHAS_TOUCH=1

	#TFT Configs
	-DDONT_USE_INPUT_TASK=1 # TFT and Touch share the same SPI bus
	-DILI9341_DRIVER=1
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BL=27
	-DTFT_IPS=0
	-DTFT_COL_OFS1=0
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=0
	-DTFT_ROW_OFS2=0
	-DTOUCH_CS=33
	-DCYD28_TouchR_IRQ=36
	-DCYD28_TouchR_MISO=12
	-DCYD28_TouchR_MOSI=13
	-DCYD28_TouchR_CSK=14
	-DCYD28_TouchR_CS=33
	-DSDCARD_CS=5
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

	# Configuração de brilho do display
	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000

lib_ignore =
	SensorLib
	XPowersLib

[elecrowS3]
board = esp32s3-16mb-psram
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/elecrow>
build_src_flags =
	-DPART_16MB=1
	-DELECROWS3
	# Configurações de hardware
	-DROTATION=1
	-DHAS_BTN=0
	-DSEL_BTN=-1
	-DUP_BTN=-1
	-DDW_BTN=-1
	-DBTN_ACT=LOW
	-DBTN_ALIAS='\"Sel\"'
	-DMINBRIGHT=190
	-DBACKLIGHT=27
	-DLED=-1
	-DLED_ON=LOW
	-DHAS_TOUCH=1

	# Configuração de brilho do display
	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000

lib_deps =
	${env.lib_deps}
	https://github.com/mmMicky/TouchLib

lib_ignore =
	SensorLib
	XPowersLib

[env:elecrow-24B]
extends=elecrow
build_src_flags =
	${elecrow.build_src_flags}
	-D HAS_RESISTIVE_TOUCH=1
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D CYD28_TouchR_ROT=6
	-D CYD28_TouchR_CAL_XMIN=557
	-D CYD28_TouchR_CAL_XMAX=3263
	-D CYD28_TouchR_CAL_YMIN=369
	-D CYD28_TouchR_CAL_YMAX=3493


[env:elecrow-28B]
extends=elecrow
build_src_flags =
	${elecrow.build_src_flags}
 	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D HAS_RESISTIVE_TOUCH=1
	-D CYD28_TouchR_ROT=6
	-D CYD28_TouchR_CAL_XMIN=189
	-D CYD28_TouchR_CAL_XMAX=3416
	-D CYD28_TouchR_CAL_YMIN=359
	-D CYD28_TouchR_CAL_YMAX=3439

[env:elecrow-35B]
extends=elecrow
build_src_flags =
	${elecrow.build_src_flags}
	-D ILI9488_DRIVER=1
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=480
	-D HAS_RESISTIVE_TOUCH=1
	-D CYD28_TouchR_ROT=6
	-D CYD28_TouchR_CAL_XMIN=353
	-D CYD28_TouchR_CAL_XMAX=3568
	-D CYD28_TouchR_CAL_YMIN=269
	-D CYD28_TouchR_CAL_YMAX=3491
build_unflags =
	-DILI9341_DRIVER=1

[env:elecrow-35Bv2_2]
extends=env:elecrow-35B
build_src_flags =
	${elecrow.build_src_flags}
	-DCYD28_TouchR_CS=12
	-DTFT_MISO=33
