; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-tab5]
board = m5stack-tab5
extra_scripts =
	pre:support_files/prep_web_files.py
	post:support_files/merge.py
board_build.partitions = support_files/custom_16Mb_p4.csv
build_src_filter =${env.build_src_filter} +<../boards/m5stack-tab5>
build_src_flags =
	-DOTA_TAG='"tab5"'
	;-DPART_04MB=1
	;-DPART_08MB=1
	-DPART_16MB=1
	-DCORE_DEBUG_LEVEL=2

	-DUSE_M5GFX=1

	-DROTATION=3
	-DHAS_BTN=1
	-DSEL_BTN=37
	-DUP_BTN=35
	-DDW_BTN=39
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"M5"'
	-DLED=19
	-DLED_ON=HIGH
	-DBACKLIGHT=27
	-DMINBRIGHT=190
	-DFP=3
	-DFM=6
	-DFG=9

	-DHAS_TOUCH=1

	-DDSI_DRIVER=1
	-DTFT_WIDTH=720
	-DTFT_HEIGHT=1280
	-DTFT_CS=5
	-DTFT_DC=14
	-DTFT_RST=12
	-DTOUCH_CS=-1
	-DTFT_MOSI=15
	-DTFT_SCLK=13
	-DTFT_BL=27

	-DGFX_BL=27
	-DTFT_IPS=0
	-DTFT_COL_OFS1=0
	-DTFT_ROW_OFS1=32
	-DTFT_COL_OFS2=0
	-DTFT_ROW_OFS2=0

	-DSDCARD_CS=42
	-DSDCARD_SCK=43
	-DSDCARD_MISO=39
	-DSDCARD_MOSI=44

	-D SDIO2_CLK=GPIO_NUM_12
	-D SDIO2_CMD=GPIO_NUM_13
	-D SDIO2_D0=GPIO_NUM_11
	-D SDIO2_D1=GPIO_NUM_10
	-D SDIO2_D2=GPIO_NUM_9
	-D SDIO2_D3=GPIO_NUM_8
	-D SDIO2_RST=GPIO_NUM_15


lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.2

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino

