[env:lilygo-t-hmi]
board = esp32s3-16mb-psram
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-hmi>
build_src_flags =
	-DOTA_TAG='"t-hmi"'
	-D BTN_ALIAS='"OK"'

	-D SDM=SD_MMC
	-D PIN_SD_CMD=11
	-D PIN_SD_CLK=12
	-D PIN_SD_D0=13

	-D HAS_TOUCH=1
	-D HAS_RESISTIVE_TOUCH=1
	-D TOUCH_XPT2046_SPI
	-D CYD28_TouchR_IRQ=9
	-D CYD28_TouchR_MISO=4
	-D CYD28_TouchR_MOSI=3
	-D CYD28_TouchR_CLK=1
	-D CYD28_TouchR_CS=2

	-DANALOG_BAT_PIN=5
	-D BAT_PIN=5

	-DDEVICE_NAME='"Lilygo T-HMI"'

	-D HAS_SCREEN=1
	-D ROTATION=0
	-D USER_SETUP_LOADED
	-D ST7789_DRIVER=1
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_INVERSION_OFF=1
	-D TFT_PARALLEL_8_BIT=1
	-D TFT_CS=6
	-D TFT_DC=7
	-D TFT_RST=-1
	-D TFT_WR=8
	-D TFT_RD=-1
	-D TFT_D0=48
	-D TFT_D1=47
	-D TFT_D2=39
	-D TFT_D3=40
	-D TFT_D4=41
	-D TFT_D5=42
	-D TFT_D6=45
	-D TFT_D7=46
	-D TFT_BL=38
	-D SMOOTH_FONT=1


	-D GFX_BL=38
	-D TFT_IPS=0
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

lib_ignore =
	SensorLib
	XPowersLib
