; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:smoochiee-board]
board = esp32s3-16mb-psram
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/smoochiee-board>
build_src_flags =
	-DOTA_TAG='"smoochiee_v2"'
	-Os
	-DPART_16MB=1

	-D BTN_ALIAS='"OK"'
	-D HAS_5_BUTTONS=1
	-D HAS_BTN=1
	-D SEL_BTN=0
	-D UP_BTN=41
	-D DW_BTN=40
	-D R_BTN=38
	-D L_BTN=39
	-D BTN_ACT=LOW

	-D HAS_SCREEN=1
	-D ROTATION=1
	-D MINBRIGHT=160

	-D ST7789_DRIVER=1
	-D TFT_WIDTH=170
	-D TFT_HEIGHT=320
	-D TFT_BL=6
	-D TFT_RST=16
	-D TFT_DC=15
	-D TFT_MOSI=17
	-D TFT_MISO=8
	-D TFT_SCLK=18
	-D TFT_CS=7

	-D GFX_BL=21
	-D TFT_IPS=1
	-D TFT_COL_OFS1=35
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=35
	-D TFT_ROW_OFS2=0

	-D CC1101_SS_PIN=46
	-D NRF24_SS_PIN=14

	-D SDCARD_CS=3
	-D SDCARD_SCK=18
	-D SDCARD_MISO=8
	-D SDCARD_MOSI=17

	-D GROVE_SDA=47
	-D GROVE_SCL=48

lib_ignore =
	SensorLib
